### ISSUE TITLE
Reimplement Certificate Import button

### ISSUE THREAD

**Issue by JesseRacine** [comp500/SSLSocks#4]
Where should certificates be placed in the filesystem?

**Comment by comp500** [comment]
You can't place them yourself due to android filesystem limitations (unless you use a root file explorer). I did [implement](https://github.com/comp500/SSLSocks/blob/master/app/src/main/java/link/infra/sslsocks/gui/MainActivity.java#L283) a certificate import button, but for some reason I [commented it out](https://github.com/comp500/SSLSocks/blob/a19f9068fc83a3b7d19e66405e93016680a15776/app/src/main/res/menu/menu_main.xml#L17). I'll investigate this and see if I can add it back.

**Comment by JesseRacine** [comment]
Thanks for responding. Actually I did figure out how to use adb and copy the certificate into the app's data directory. I got that working, but it is kind of awkward.

**Comment by comp500** [comment]
Should be fixed with [version 0.0.3-beta](https://github.com/comp500/SSLSocks/releases/tag/0.0.3-beta). If you have any problems with it, submit another comment here.
